### ISSUE TITLE
question: passing an object to usage()

### ISSUE THREAD

**Issue by boneskull** [cli-kit/lipsum#3]
This seems undocumented, and in `lipsum.js` is the only place I see it:

``` js
  var hints = {
    values: {
      format: formats,
      align: alignments,
      sort: list,
      maximum: [60, 240]
    }
  }
  this
    .configure(conf)
    .usage(hints);
```

What is the API for passing an object to `usage()`?  Everywhere else I see a string.

thanks,
Chris

**Comment by tmpfs** [comment]
Like many other parts of the codebase this functionality still needs documenting, I am replacing this with a new issue:

https://github.com/freeformsystems/cli-command/issues/79

Thanks for bringing this up, as soon as I find the time I will document usage().
